# site settings
title: OTZO
subtitle: by tchzo
email: contact@tchzo.com
description: A solution designed to manage client and your auto garage.
baseurl: # the subpath of your site, e.g. /blog
url: https://otzo.tchzo.com/
author: otzo
street_address: 1569, 19th Main, AECS A block, Singasandra
city: Bangalore
state: Karnataka
zip_code: 560068
country: India
phone: +91 80 4956 3512

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
